config/routes.rb
Rails.application.routes.draw do
  root to: 'students#index'
  resources :students

end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
  	@students = Student.all
  end
  def show
  	@student = Student.find(params[:id])
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Schoolapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/index.html.erb
<h1>List of students </h1>
<ul>
 	<% @students.each do |student| %>
 	  <li>
			<%= link_to student.name,student_path(student) %>
		<% end %>	
	  </li>
 </ul>	

app/views/students/show.html.erb
<h2>
	<%= "#{@student.name} information" %>
</h2>
<%= "Age: #{@student.age}" %>
</br>
<%= "Email: #{@student.email}" %>
<%= link_to "Back to Index",students_path) %>